version: '3.9'

services:
  flask-app-hash:
    build: ./app
    image: sdi/flask_app_hash:latest
    container_name: my-flask-app-hash
    ports:
      - 5000:5000
    volumes:
      - ./app:/app # Temporal NOT use in production